# Configuration for Rasa Core (dialogue management)
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
language: es
# The config file defines the pipeline and policies.
# The pipeline determines how the NLU component processes user messages.
pipeline:
  # Featurizers for text data
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
  features:
  - ["low", "title", "upper", "BOS", "EOS", "prefix5", "suffix5"]
- name: CountVectorsFeaturizer
  analyzer: word
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

  # Main NLU machine learning components
- name: DIETClassifier   # Intent classification and entity extraction
  epochs: 200
  constrain_negatives: true
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector   # Handles chitchat and frequently asked questions
  epochs: 100
  constrain_similarities: true

# The policies determine how the Core component chooses the next action.
policies:
- name: RulePolicy   # Handles specific, hard-coded rules (e.g., greetings, goodbyes)
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy   # Remembers exact conversation turns
- name: TEDPolicy   # State-of-the-art dialogue management policy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20251018-210555-energetic-inventory
