services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /srv/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  rag-api:
    build: .
    container_name: rag-api
    # depends_on:
    #   - ollama
    ports:
      - "8001:8001"
    environment:
      - OLLAMA_URL=http://172.16.2.90:11434
      - CHROMA_HOST=172.16.2.66
      - CHROMA_PORT=8000
    restart: unless-stopped